spring:
  profiles:
    active: default
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
server:
  port: 8080

steam:
  api:
    key: 88721AB6DB5DA8E1384A8DB9B493690C
    url: http://api.steampowered.com

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG



db:
  rds:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    secret:
    username-deploy: sa
    secret-deploy:
    change-log: classpath:db/changelog/db.changelog-master.yml
    driver: org.h2.Driver
