spring:
  profiles:
    active: default
server:
  port: 8080

steam:
  api:
    key: 88721AB6DB5DA8E1384A8DB9B493690C
    url: http://api.steampowered.com

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
